package com.fieldcrm.android.ui.screens.application

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.fieldcrm.android.ui.components.*
import com.fieldcrm.android.ui.theme.FieldIcons
import com.fieldcrm.android.ui.theme.FieldTheme
import com.fieldcrm.shared.model.LoanApplicationModel
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DisbursementFormScreen(
    application: LoanApplicationModel,
    isSubmitting: Boolean = false,
    onRecordDisbursement: (Double, String, String, String, Double, String, String) -> Unit =
        { _, _, _, _, _, _, _ -> },
    onBack: () -> Unit
) {
    var actualAmount by remember { mutableStateOf(application.amount?.toString() ?: "") }
    var disbursementDate by remember { mutableStateOf("2026-08-02") }
    var paymentMethod by remember { mutableStateOf("bank_transfer") }
    var bankReference by remember { mutableStateOf("") }
    var interestRate by remember { mutableStateOf(application.interest_rate?.toString() ?: "15.0") }
    var repaymentFrequency by remember { mutableStateOf(application.repayment_frequency ?: "monthly") }
    var scheduleMethod by remember { mutableStateOf("reducing_balance") }

    var isOfferGenerated by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            FieldTopAppBar(
                title = "Record Disbursement",
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            imageVector = FieldIcons.ArrowBackOutlined,
                            contentDescription = "Back",
                            tint = androidx.compose.ui.graphics.Color.White
                        )
                    }
                }
            )
        },
        bottomBar = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(FieldTheme.colors.gray950)
                    .border(width = 0.5.dp, color = FieldTheme.colors.gray800)
                    .padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                DecisionImpactNotice(
                    "Recording disbursement registers this transaction in Mainstreet MMFB ledger and starts interest calculations."
                )
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    OutlinedButton(
                        onClick = { isOfferGenerated = true },
                        enabled = !isOfferGenerated && !isSubmitting,
                        modifier = Modifier.weight(1.2f)
                    ) {
                        Text(if (isOfferGenerated) "Offer Letter Active" else "Generate Offer", color = if (isOfferGenerated) FieldTheme.colors.statusSuccess else FieldTheme.colors.purple400)
                    }
                    PrimaryButton(
                        text = if (isSubmitting) "Processing..." else "Record Disbursement",
                        onClick = {
                            val amt = actualAmount.toDoubleOrNull() ?: 0.0
                            if (amt > 0.0) {
                                onRecordDisbursement(
                                    amt,
                                    disbursementDate,
                                    paymentMethod,
                                    bankReference,
                                    interestRate.toDoubleOrNull() ?: 0.0,
                                    repaymentFrequency,
                                    scheduleMethod
                                )
                            }
                        },
                        enabled = (actualAmount.toDoubleOrNull() ?: 0.0) > 0.0 && bankReference.isNotBlank() && isOfferGenerated && !isSubmitting,
                        modifier = Modifier.weight(1.5f)
                    )
                }
            }
        },
        containerColor = FieldTheme.colors.gray950
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(20.dp)
        ) {
            // Z2 Summary Headline Card
            FieldCard(modifier = Modifier.fillMaxWidth()) {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Column {
                            Text(
                                text = application.applicant_name ?: "Unknown Applicant",
                                style = FieldTheme.typography.bodyStrong,
                                color = FieldTheme.colors.gray100
                            )
                            Text(
                                text = "Ref: ${application.ref_no}",
                                style = FieldTheme.typography.label,
                                color = FieldTheme.colors.gray400
                            )
                        }
                        StatusChip(label = application.displayStatus)
                    }
                    Divider(color = FieldTheme.colors.gray800, modifier = Modifier.padding(vertical = 4.dp))
                    Text(
                        text = "APPROVED PRINCIPAL AMOUNT",
                        style = FieldTheme.typography.label,
                        color = FieldTheme.colors.gray400
                    )
                    Text(
                        text = "₦${String.format(Locale.US, "%,.2f", application.amount ?: 0.0)}",
                        style = FieldTheme.typography.display.copy(fontSize = 32.sp),
                        color = FieldTheme.colors.purple400
                    )
                }
            }

            // Z4 Form grouped by topic
            SectionCard(title = "Disbursement Parameters") {
                Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    OutlinedTextField(
                        value = actualAmount,
                        onValueChange = { actualAmount = it },
                        label = { Text("Actual Disbursed Amount (₦)") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                    OutlinedTextField(
                        value = disbursementDate,
                        onValueChange = { disbursementDate = it },
                        label = { Text("Disbursement Date (YYYY-MM-DD)") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                    OutlinedTextField(
                        value = paymentMethod,
                        onValueChange = { paymentMethod = it },
                        label = { Text("Payment Method / Channel") },
                        placeholder = { Text("e.g. bank_transfer") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                    OutlinedTextField(
                        value = bankReference,
                        onValueChange = { bankReference = it },
                        label = { Text("Bank Reference / Transaction ID") },
                        placeholder = { Text("e.g. TXN982348234") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                }
            }

            SectionCard(title = "Lending Rates & Schedule Configuration") {
                Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    OutlinedTextField(
                        value = interestRate,
                        onValueChange = { interestRate = it },
                        label = { Text("Interest Rate (% per annum)") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                    OutlinedTextField(
                        value = repaymentFrequency,
                        onValueChange = { repaymentFrequency = it },
                        label = { Text("Repayment Frequency") },
                        placeholder = { Text("e.g. monthly") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                    OutlinedTextField(
                        value = scheduleMethod,
                        onValueChange = { scheduleMethod = it },
                        label = { Text("Amortization Schedule Method") },
                        placeholder = { Text("e.g. reducing_balance") },
                        modifier = Modifier.fillMaxWidth(),
                        colors = TextFieldDefaults.colors(focusedContainerColor = FieldTheme.colors.gray900, unfocusedContainerColor = FieldTheme.colors.gray900, focusedTextColor = FieldTheme.colors.gray100, unfocusedTextColor = FieldTheme.colors.gray100)
                    )
                }
            }

            Spacer(modifier = Modifier.height(100.dp))
        }
    }
}
