-- Phase 5: effective workflow, permission bundles, maker-checker, delegation and credit policy.
CREATE TABLE permissions (code TEXT PRIMARY KEY, description TEXT NOT NULL);
CREATE TABLE role_permissions (role TEXT NOT NULL, permission_code TEXT NOT NULL REFERENCES permissions(code), PRIMARY KEY(role,permission_code));
INSERT INTO permissions(code,description) VALUES
('customer:create','Create customers'),('application:submit','Submit applications'),('credit:review','Perform credit review'),
('loan:approve','Approve loans'),('document:verify','Verify documents'),('visit:create','Create visits'),
('audit:view','View independent audit'),('config:manage','Manage institution configuration'),('portfolio:reassign','Reassign portfolios');
INSERT INTO role_permissions VALUES
('account_officer','customer:create'),('account_officer','application:submit'),('account_officer','visit:create'),
('credit_analyst','credit:review'),('credit_analyst','document:verify'),('branch_manager','loan:approve'),
('branch_supervisor','loan:approve'),('ed','loan:approve'),('md','loan:approve'),('auditor','audit:view'),
('configuration_admin','config:manage'),('system_admin','portfolio:reassign');

CREATE TABLE workflow_definitions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,configuration_version_id UUID NOT NULL REFERENCES configuration_versions(id) ON DELETE RESTRICT,product_code TEXT NOT NULL REFERENCES loan_products(code),name TEXT NOT NULL,UNIQUE(configuration_version_id,product_code));
CREATE TABLE workflow_stage_definitions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workflow_id UUID NOT NULL REFERENCES workflow_definitions(id) ON DELETE CASCADE,stage_key TEXT NOT NULL,label TEXT NOT NULL,position INTEGER NOT NULL,permission_code TEXT NOT NULL REFERENCES permissions(code),condition JSONB NOT NULL DEFAULT '{}'::jsonb,return_stage_key TEXT,UNIQUE(workflow_id,stage_key),UNIQUE(workflow_id,position));
CREATE TABLE approval_matrix_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,configuration_version_id UUID NOT NULL REFERENCES configuration_versions(id) ON DELETE RESTRICT,product_code TEXT REFERENCES loan_products(code),min_amount NUMERIC(15,2),max_amount NUMERIC(15,2),risk_level TEXT,branch_id UUID REFERENCES branches(id),collateral_type TEXT,customer_type TEXT,minimum_exception_count INTEGER,required_stage_key TEXT NOT NULL,priority INTEGER NOT NULL DEFAULT 100);
CREATE TABLE application_workflow_snapshots (application_id UUID PRIMARY KEY REFERENCES loan_applications(id) ON DELETE CASCADE,org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,configuration_version_id UUID REFERENCES configuration_versions(id) ON DELETE RESTRICT,stages JSONB NOT NULL,approval_rules JSONB NOT NULL,captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE application_actor_actions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,actor_id UUID NOT NULL REFERENCES users(id),action_type TEXT NOT NULL CHECK(action_type IN('originate','recommend','approve','disburse','reverse')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE UNIQUE INDEX maker_checker_action_once ON application_actor_actions(application_id,actor_id,action_type);
CREATE TABLE staff_delegations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,delegator_id UUID NOT NULL REFERENCES users(id),delegate_id UUID NOT NULL REFERENCES users(id),permission_code TEXT NOT NULL REFERENCES permissions(code),starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,created_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),CHECK(delegator_id<>delegate_id),CHECK(ends_at>starts_at));
CREATE TABLE portfolio_reassignments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,from_user_id UUID NOT NULL REFERENCES users(id),to_user_id UUID NOT NULL REFERENCES users(id),scope JSONB NOT NULL,counts JSONB NOT NULL,reason TEXT NOT NULL,created_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE credit_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,configuration_version_id UUID NOT NULL REFERENCES configuration_versions(id) ON DELETE RESTRICT,product_code TEXT REFERENCES loan_products(code),rule_key TEXT NOT NULL,label TEXT NOT NULL,fact_key TEXT NOT NULL,operator TEXT NOT NULL CHECK(operator IN('lte','lt','gte','gt','eq','neq')),threshold JSONB NOT NULL,severity TEXT NOT NULL DEFAULT 'fail',UNIQUE(configuration_version_id,rule_key));
CREATE TABLE credit_rule_results (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,rule_id UUID NOT NULL REFERENCES credit_rules(id) ON DELETE RESTRICT,outcome TEXT NOT NULL CHECK(outcome IN('pass','fail','not_applicable')),actual_value JSONB,evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(application_id,rule_id));
CREATE TABLE manual_credit_bureau_evidence (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,provider TEXT NOT NULL,checked_at DATE NOT NULL,result TEXT NOT NULL CHECK(result IN('pass','pass_with_conditions','review_required','fail')),document_id UUID NOT NULL REFERENCES documents(id) ON DELETE RESTRICT,assessment TEXT NOT NULL,recorded_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS owner_name TEXT; ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS forced_sale_value NUMERIC(15,2); ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS valuer TEXT; ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS valuation_date DATE; ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS insurance_details JSONB NOT NULL DEFAULT '{}'::jsonb; ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS legal_status TEXT; ALTER TABLE collateral_items ADD COLUMN IF NOT EXISTS expiry_date DATE;
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['workflow_definitions','approval_matrix_rules','application_workflow_snapshots','application_actor_actions','staff_delegations','portfolio_reassignments','credit_rules','credit_rule_results','manual_credit_bureau_evidence'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t); EXECUTE format('CREATE POLICY %I_tenant ON %I USING(org_id=NULLIF(current_setting(''app.current_org_id'',TRUE),'''')::uuid) WITH CHECK(org_id=NULLIF(current_setting(''app.current_org_id'',TRUE),'''')::uuid)',t,t); END LOOP; END $$;
