-- Phase 6 operational work, exceptions, SLA and collaboration.
CREATE TABLE work_tasks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,task_type TEXT NOT NULL,assigned_user_id UUID REFERENCES users(id),assigned_role TEXT,application_id UUID REFERENCES loan_applications(id) ON DELETE CASCADE,customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,priority TEXT NOT NULL DEFAULT 'normal' CHECK(priority IN('low','normal','high','urgent')),due_at TIMESTAMPTZ,status TEXT NOT NULL DEFAULT 'new' CHECK(status IN('new','in_progress','waiting','returned','completed','cancelled')),created_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ,CHECK(assigned_user_id IS NOT NULL OR assigned_role IS NOT NULL));
CREATE TABLE operational_exceptions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,category TEXT NOT NULL CHECK(category IN('cbs_sync','customer_mismatch','loan_mismatch','missing_document','ocr','workflow','sla','duplicate_customer','policy','integration')),application_id UUID REFERENCES loan_applications(id) ON DELETE CASCADE,customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,severity TEXT NOT NULL DEFAULT 'medium',summary TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','investigating','resolved','dismissed')),assigned_to UUID REFERENCES users(id),source_ref TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),resolved_at TIMESTAMPTZ);
CREATE TABLE sla_stage_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,stage_key TEXT NOT NULL,entered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),exited_at TIMESTAMPTZ,target_hours INTEGER NOT NULL);
CREATE TABLE sla_pauses(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,stage_event_id UUID NOT NULL REFERENCES sla_stage_events(id) ON DELETE CASCADE,reason TEXT NOT NULL CHECK(reason IN('awaiting_customer_document','external_verification_pending','legal_document_pending','cbs_unavailable')),started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),ended_at TIMESTAMPTZ,created_by UUID NOT NULL REFERENCES users(id));
CREATE TABLE disbursement_conditions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,condition_type TEXT NOT NULL CHECK(condition_type IN('insurance','legal_search','equity_contribution','original_collateral','guarantor_execution','other')),description TEXT NOT NULL,mandatory BOOLEAN NOT NULL DEFAULT TRUE,satisfied_at TIMESTAMPTZ,satisfied_by UUID REFERENCES users(id),evidence_document_id UUID REFERENCES documents(id));
CREATE TABLE policy_waivers(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,policy_violated TEXT NOT NULL,expected_requirement TEXT NOT NULL,actual_condition TEXT NOT NULL,requestor_id UUID NOT NULL REFERENCES users(id),reason TEXT NOT NULL,approver_id UUID REFERENCES users(id),approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE application_notes(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,application_id UUID NOT NULL REFERENCES loan_applications(id) ON DELETE CASCADE,category TEXT NOT NULL CHECK(category IN('general','credit','visit','collection','legal','audit','internal_confidential')),body TEXT NOT NULL,created_by UUID NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE note_mentions(note_id UUID NOT NULL REFERENCES application_notes(id) ON DELETE CASCADE,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(note_id,user_id));
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['work_tasks','operational_exceptions','sla_stage_events','sla_pauses','disbursement_conditions','policy_waivers','application_notes'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t); EXECUTE format('CREATE POLICY %I_tenant ON %I USING(org_id=NULLIF(current_setting(''app.current_org_id'',TRUE),'''')::uuid) WITH CHECK(org_id=NULLIF(current_setting(''app.current_org_id'',TRUE),'''')::uuid)',t,t); END LOOP; END $$;
